### ISSUE TITLE
Algorithm constraints check failed: MD5withRSA for 2 cxf/wss4j microbenchmarks 

### ISSUE THREAD

**Issue by rsvoboda** [coheigea/testcases#9]
When running https://github.com/coheigea/testcases/tree/master/apache/cxf/cxf-benchmarks/cxf-jmh with Java 8 I see 2 failures because of `Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed: MD5withRSA`

Benchmarks:
 * org.apache.coheigea.cxf.jmh.benchmark.wssec.SignatureReferenceBenchmark.signatureX509KeyIdentifier
 * org.apache.coheigea.cxf.jmh.benchmark.wssec.SignatureReferenceBenchmark.signatureBST

It could be related to changes in Java (7u40) - restrictions on x.509 certificates with RSA keys and minimal length.
I tried to use Java 7 update 25 and all tests went well without any exception.

Full stacktrace
```
org.apache.wss4j.common.ext.WSSecurityException: Error during certificate path validation: Algorithm constraints check failed: MD5withRSA
Original Exception was java.security.cert.CertPathValidatorException: Algorithm constraints check failed: MD5withRSA
	at org.apache.wss4j.common.crypto.Merlin.verifyTrust(Merlin.java:933)
	at org.apache.wss4j.dom.validate.SignatureTrustValidator.verifyTrustInCerts(SignatureTrustValidator.java:108)
	at org.apache.wss4j.dom.validate.SignatureTrustValidator.validate(SignatureTrustValidator.java:64)
	at org.apache.wss4j.dom.processor.SignatureProcessor.handleToken(SignatureProcessor.java:184)
	at org.apache.wss4j.dom.engine.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:344)
	at org.apache.coheigea.cxf.jmh.benchmark.wssec.SignatureReferenceBenchmark.doSignature(SignatureReferenceBenchmark.java:117)
	at org.apache.coheigea.cxf.jmh.benchmark.wssec.SignatureReferenceBenchmark.signatureBST(SignatureReferenceBenchmark.java:80)
	at org.apache.coheigea.cxf.jmh.benchmark.wssec.generated.SignatureReferenceBenchmark_signatureBST_jmhTest.signatureBST_avgt_jmhStub(SignatureReferenceBenchmark_signatureBST_jmhTest.java:182)
	at org.apache.coheigea.cxf.jmh.benchmark.wssec.generated.SignatureReferenceBenchmark_signatureBST_jmhTest.signatureBST_AverageTime(SignatureReferenceBenchmark_signatureBST_jmhTest.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:464)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:448)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed: MD5withRSA
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:219)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
	at org.apache.wss4j.common.crypto.Merlin.verifyTrust(Merlin.java:911)
	... 20 more
```

**Comment by rsvoboda** [comment]
Sorry for false alarm, problem is on my side ... I didn't have unlimited cryptography and Bouncy Castle with my previous JDK 8 runs :(
